import { defineConfig } from "vite-plus"

const ignorePatterns = [
  "node_modules",
  ".next",
  ".source",
  "dist",
  "build",
  "opensrc",
  "scripts",
  "e2e",
  "coverage",
  "playwright-report",
  "test-results",
  "blob-report",
  "graphify-out",
  ".vite-hooks",
  ".vscode",
  ".agents",
  "bun.lock",
  "**/*.d.ts",
  "**/*.tsbuildinfo",
  "src/types/env.d.ts",
  "src/integrations/next-intl/*.d.json.ts",
  "src/integrations/drizzle-orm/migrations/**",
]

export default defineConfig({
  fmt: {
    arrowParens: "always",
    bracketSpacing: true,
    endOfLine: "lf",
    ignorePatterns,
    jsxSingleQuote: false,
    printWidth: 140,
    semi: false,
    singleQuote: false,
    sortImports: {
      customGroups: [
        {
          elementNamePattern: ["server-only"],
          groupName: "server-only",
          modifiers: ["side_effect"],
        },
        {
          elementNamePattern: ["react", "react/**", "next", "next/**"],
          groupName: "react-and-next",
        },
        {
          elementNamePattern: ["~/src/environment", "~/src/environment/**"],
          groupName: "environment",
        },
        {
          elementNamePattern: ["~/src/constants", "~/src/constants/**"],
          groupName: "constants",
        },
        {
          elementNamePattern: ["~/src/providers/**"],
          groupName: "providers",
        },
        {
          elementNamePattern: ["~/src/integrations/**"],
          groupName: "integrations",
        },
        {
          elementNamePattern: ["~/src/lib/**"],
          groupName: "lib",
        },
        {
          elementNamePattern: ["~/src/hooks/**"],
          groupName: "hooks",
        },
        {
          elementNamePattern: ["~/src/components/shadcn/**"],
          groupName: "components-shadcn",
        },
        {
          elementNamePattern: ["~/src/components/custom/**"],
          groupName: "components-custom",
        },
        {
          elementNamePattern: ["~/src/components", "~/src/components/**"],
          groupName: "components-other",
        },
        {
          elementNamePattern: ["~/src/styles", "~/src/styles/**"],
          groupName: "styles",
        },
      ],
      groups: [
        "server-only",
        { newlinesBetween: true },
        "react-and-next",
        ["builtin", "external"],
        "environment",
        "constants",
        "providers",
        "integrations",
        "lib",
        "hooks",
        "components-shadcn",
        "components-custom",
        "styles",
        ["internal", "parent", "sibling", "index"],
        "unknown",
      ],
      ignoreCase: true,
      newlinesBetween: true,
      sortSideEffects: true,
    },
    sortTailwindcss: {
      attributes: ["className", "classList"],
      functions: ["clsx", "cn", "cva", "tw"],
      stylesheet: "./src/styles/globals.css",
    },
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
  lint: {
    categories: {
      correctness: "error",
      pedantic: "error",
      perf: "error",
      style: "error",
      suspicious: "error",
    },
    ignorePatterns,
    options: {
      denyWarnings: true,
      reportUnusedDisableDirectives: "error",
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ["src/components/shadcn/label.tsx"],
        rules: {
          "jsx-a11y/label-has-associated-control": "off",
        },
      },
      {
        files: ["src/integrations/next-intl/i18n.formats.ts"],
        rules: {
          "eslint/no-inline-comments": "off",
        },
      },
      {
        files: ["src/integrations/next-intl/i18n.utils.ts"],
        rules: {
          "import/no-nodejs-modules": "off",
        },
      },
    ],
    plugins: ["typescript", "react", "react-perf", "jsx-a11y", "unicorn", "import", "promise", "vitest", "oxc", "eslint"],
    rules: {
      "capitalized-comments": "off",
      "consistent-return": "off",
      "eslint/no-magic-numbers": [
        "error",
        {
          ignore: [0],
          ignoreArrayIndexes: true,
          ignoreDefaultValues: true,
          ignoreTypeIndexes: true,
        },
      ],
      "func-style": "off",
      "id-length": "off",
      "import/consistent-type-specifier-style": "off",
      "import/exports-last": "off",
      "import/group-exports": "off",
      "import/max-dependencies": "off",
      "import/no-named-export": "off",
      "import/no-namespace": "off",
      "import/no-unassigned-import": "off",
      "import/prefer-default-export": "off",
      "max-lines": ["error", { max: 800 }],
      "max-lines-per-function": ["error", { max: 150 }],
      "max-statements": ["error", { max: 20 }],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              message: "Import from `~/src/integrations/next-intl/i18n.navigation` instead.",
              name: "next/link",
            },
            {
              importNames: ["redirect", "permanentRedirect", "useRouter", "usePathname"],
              message: "Import from `~/src/integrations/next-intl/i18n.navigation` instead.",
              name: "next/navigation",
            },
          ],
        },
      ],
      "no-ternary": "off",
      "prefer-arrow-callback": "off",
      "react/jsx-max-depth": ["error", { max: 5 }],
      "react/jsx-props-no-spreading": "off",
      "react/react-in-jsx-scope": "off",
      "sort-imports": "off",
      "typescript/no-explicit-any": "error",
      "typescript/no-floating-promises": "error",
      "typescript/no-misused-promises": "error",
      "typescript/no-unsafe-argument": "error",
      "typescript/no-unsafe-assignment": "error",
      "typescript/no-unsafe-call": "error",
      "typescript/no-unsafe-member-access": "error",
      "typescript/no-unsafe-return": "error",
      "typescript/no-unsafe-type-assertion": "error",
      "typescript/prefer-nullish-coalescing": "error",
      "typescript/prefer-readonly-parameter-types": "off",
      "typescript/strict-boolean-expressions": "error",
      "typescript/strict-void-return": "error",
    },
  },
  oxc: {
    jsx: {
      runtime: "automatic",
    },
  },
  resolve: { tsconfigPaths: true },
  staged: {
    "*": "vp check --fix",
  },
  test: {
    environment: "jsdom",
    exclude: ["node_modules/**", ".next/**", "dist/**", "build/**", "e2e/**", "opensrc/**", "src/integrations/drizzle-orm/migrations/**"],
    include: ["src/**/*.{test,spec}.{ts,tsx}"],
    isolate: false,
    passWithNoTests: true,
    pool: "threads",
  },
})
