// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "landingPage": {
    "metadata": {
      "description": "Professional full-stack starter for building SaaS applications."
    },
    "welcome": "Welcome to the {name} page!"
  },
  "appPage": {
    "metadata": {
      "description": "Signed-in app area."
    },
    "welcome": "App — {name}"
  }
};
export default messages;