// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "components": {
    "shadcn": {
      "breadcrumb": {
        "navLabel": "Breadcrumb",
        "more": "More"
      },
      "carousel": {
        "nextSlide": "Next slide",
        "previousSlide": "Previous slide",
        "carouselLabel": "Carousel"
      },
      "dialog": {
        "close": "Close"
      },
      "command": {
        "title": "Command palette",
        "description": "Search for a command to run..."
      },
      "pagination": {
        "navLabel": "Pagination",
        "previousPage": "Previous",
        "nextPage": "Next",
        "goToPreviousPage": "Go to previous page",
        "goToNextPage": "Go to next page",
        "morePages": "More pages"
      },
      "sheet": {
        "close": "Close"
      }
    },
    "custom": {
      "themeSwitch": {
        "label": "Choose a theme",
        "placeholder": "Theme",
        "light": "Light",
        "dark": "Dark",
        "system": "System"
      }
    }
  },
  "landingPage": {
    "metadata": {
      "description": "Professional full-stack starter for building SaaS applications."
    },
    "welcome": "Welcome to the {name} page!",
    "hero": {
      "badge": "424 Stars on GitHub",
      "titlePart1": "Fast-Track Your Business Launch with ",
      "titlePart2": "SaaSy Land",
      "description": "Your shortcut to startup success. The ultimate, modern, open-source Next.js template, with everything you need set up and ready to use.",
      "startBuilding": "Start Building",
      "viewRecipes": "Explore Pro Recipes"
    },
    "techMarquee": {
      "nextjs": "Next.js",
      "neon": "Neon",
      "stripe": "Stripe",
      "resend": "Resend",
      "drizzle": "Drizzle ORM",
      "tailwind": "Tailwind",
      "shadcn": "ShadCN/UI",
      "elysia": "Elysia",
      "zod": "Zod"
    },
    "benefits": {
      "titlePart1": "Why Should ",
      "titlePart2": "You Care?",
      "description": "Your competitors are already using SaaSy Land and similar products, gaining time and competitive advantage. Don't get left behind!",
      "cards": {
        "timeSaver": {
          "badge": "Incredible Time Saver",
          "title": "Get a Head Start on Your Competitors",
          "description": "Since everything is professionally configured and up to standards, you save a tremendous amount of time and effort, which you can now spend focusing on what really matters: your core business offering."
        },
        "modernTech": {
          "badge": "Latest and Greatest",
          "title": "Take Advantage of Modern Technologies",
          "description": "We are constantly updating our templates to take advantage of the latest and greatest technologies, so you can be sure your website is always fast."
        },
        "quality": {
          "badge": "High Quality Implementation",
          "title": "Know Everything Works As Expected",
          "description": "We spent countless hours researching, exploring docs and testing the best way to implement features. We have done the hard work so you don't have to."
        },
        "flexibility": {
          "badge": "Flexibility and Support",
          "title": "Easily Customize Every Single Detail",
          "description": "With the help of our detailed documentation, you can now easily customize every single detail of the template. Should you need any help, we are a message away."
        }
      },
      "stats": {
        "visits": "162.9k",
        "visitsLabel": "Last 7 Days Website Visits",
        "increase": "22% increase from Last Week"
      }
    },
    "features": {
      "titlePart1": "Discover Our ",
      "titlePart2": "Wholesome Features",
      "description": "Everything you need out of the box. No fluff, just the essentials built right.",
      "list": {
        "auth": {
          "title": "Authentication",
          "description": "Secure login, registration, and social OAuth providers already configured via Better Auth."
        },
        "db": {
          "title": "Database ORM",
          "description": "Fully typed database operations with Drizzle. Seamless integrations with PostgreSQL."
        },
        "stripe": {
          "title": "Stripe Payments",
          "description": "Handle subscriptions, one-time payments, and robust webhook listeners right out of the box."
        },
        "email": {
          "title": "Email Templates",
          "description": "Beautifully crafted React Email templates sent flawlessly via modern APIs."
        },
        "seo": {
          "title": "SEO Optimized",
          "description": "Dynamic meta tags, Open Graph imagery, and sitemap generation correctly structured."
        },
        "ui": {
          "title": "UI Components",
          "description": "A massive library of accessible, beautifully designed Base UI and Tailwind components."
        },
        "i18n": {
          "title": "Internationalization",
          "description": "Professional i18n setup supporting multiple languages and localized routing out of the box."
        },
        "typeSafety": {
          "title": "Full Type-Safety",
          "description": "End-to-end strict TypeScript configuration to catch bugs early and improve developer experience."
        },
        "quality": {
          "title": "Quality Implementation",
          "description": "Clean architecture and modular code designed to be scaled, maintained, and extended easily."
        },
        "performance": {
          "title": "Maximum Performance",
          "description": "Utilizing Partial Prerendering (PPR) and edge caching for blazingly fast load times."
        },
        "vercel": {
          "title": "Vercel & Bun Ready",
          "description": "Optimized for serverless edge deployment using Vercel and the blazingly fast Bun runtime."
        },
        "blog": {
          "title": "MDX Blog & Docs",
          "description": "A built-in markdown engine to write beautifully formatted blogs and comprehensive documentation."
        }
      }
    },
    "testimonials": {
      "titlePart1": "Loved by ",
      "titlePart2": "Builders"
    },
    "pricing": {
      "titlePart1": "Simple, transparent ",
      "titlePart2": "pricing",
      "description": "Everything you need to launch faster, at a fraction of the cost of developing it from scratch.",
      "monthly": "Monthly",
      "yearly": "Yearly",
      "save20": "Save 20%",
      "starter": {
        "title": "Starter",
        "description": "Perfect for side projects and early startups testing the waters.",
        "priceMonthly": "$0",
        "priceYearly": "$0",
        "period": "/mo",
        "button": "Get started for free!",
        "features": {
          "f1": "Complete Next.js 14 Source Code",
          "f2": "Database & Auth Setup",
          "f3": "Basic UI Components",
          "f4": "Advanced Stripe Integration",
          "f5": "Priority Support"
        }
      },
      "pro": {
        "badge": "Most Popular",
        "title": "Pro Builder",
        "description": "Everything you need to build and scale your SaaS to millions.",
        "priceMonthly": "$9.99",
        "priceYearly": "$7.99",
        "period": "/mo",
        "button": "Unlock PRO Features",
        "features": {
          "f1": "Everything in Starter",
          "f2": "Advanced Stripe Integration (Webhooks)",
          "f3": "Email Templates via Resend",
          "f4": "Admin Dashboard Components",
          "f5": "6 Months Priority Support"
        }
      },
      "lifetime": {
        "title": "Lifetime Access",
        "description": "Pay once and get lifetime access to all future updates and releases.",
        "priceMonthly": "$67",
        "priceYearly": "$67",
        "period": "/one-time",
        "button": "Gain Lifetime Access!",
        "features": {
          "f1": "Everything in Pro Builder",
          "f2": "Lifetime Core Updates",
          "f3": "Exclusive Discord Community",
          "f4": "Early Access to New Features",
          "f5": "Lifetime Priority Support"
        }
      }
    },
    "faq": {
      "titlePart1": "Frequently Asked ",
      "titlePart2": "Questions",
      "q1": "What is SaaSy Land?",
      "a1": "SaaSy Land is a modern, open sourced collection starter templates for Next.js 14 full-stack projects. Built with Tailwind CSS, ShadCn, Next-Auth and several databases. Branches contain stand-alone set ups, including for serverless databases like PostgreSQL with Neon and MySQL with PlanetScale, Drizzle ORM, Prisma ORM v.5, but also MongoDB and Supabase.",
      "q2": "What is included?",
      "a2": "Several configuration options are available. Depending on which repo branch you clone and decide to use, you will have a full-stack project with advanced authentication (e.g., email verification, password reset, magic link sign in, OAuth social sign in with Google and Github), synchronized with a database of your choosing. On top of that, you will have a fully functional landing page, which is extremely easy to customize, Markdown and MDX-powered blog, documentation pages, Stripe payments integration, and more.",
      "q3": "Why would I want to use SaaSy Land?",
      "a3": "Since everything is professionally pre-configured and up to the latest standards, you save a tremendous amount of time and effort, which you can now spend focusing on what really matters - building your own, unique product. And it's completely free!",
      "q4": "Is it easy to use? How do I get started?",
      "a4": "SaaSy Land is extremely easy to use. You can get started by cloning a GitHub repo and following the documentation.",
      "q5": "Can I get help and support?",
      "a5": "Feel free to email us with any questions, or start a discussion on GitHub. While we are always happy to help, please keep in mind that this is a free product, which we develop out of passion in our free time and hence, we cannot guarantee any response times.",
      "q6": "Is the product actively maintained?",
      "a6": "SaaSy Land is currently under active development. We are working on adding new features and improving the existing ones. We are also working on improving the documentation and adding more examples. Stay tuned! You may also consider signing up for our newsletter to get notified about new major releases. We will not spam you, we promise!"
    },
    "newsletter": {
      "title": "Sign Up to Our Newsletter",
      "description": "Stay in the loop with updates on new features, boilerplate releases, and startup growth tips directly to your inbox.",
      "placeholder": "Enter your email address",
      "button": "Subscribe"
    },
    "contact": {
      "title": "Let's Get in Touch",
      "description": "Feel free to email us with any questions you might have. While we are always happy to help, please keep in mind that this is a free product and we cannot guarantee any response times. We would also love to know your feedback!",
      "location": "Kraków, Poland",
      "form": {
        "firstName": "Name",
        "email": "Email Address",
        "message": "How can we help?",
        "button": "Send Message"
      }
    },
    "footer": {
      "copyright": "© {year}"
    }
  },
  "navigation": {
    "items": {
      "about": "About",
      "features": "Features",
      "pricing": "Pricing",
      "faq": "FAQ",
      "docs": "Docs",
      "blog": "Blog"
    },
    "getStarted": "Get Started"
  },
  "premiumPage": {
    "metadata": {
      "description": "Premium content for SaaSy Land."
    },
    "title": "Premium",
    "description": "Premium content for SaaSy Land."
  },
  "emails": {
    "test": {
      "title": "Test"
    },
    "resetPassword": {
      "subject": "Reset your password",
      "preview": "Reset your password for SaaSy Land",
      "heading": "Reset your password",
      "body": "Hi {name}, we received a request to reset your password. Click the button below to choose a new one.",
      "button": "Reset password",
      "footer": "If you did not request this, you can safely ignore this email."
    },
    "verifyEmail": {
      "subject": "Verify your email address",
      "preview": "Verify your email for SaaSy Land",
      "heading": "Verify your email",
      "body": "Hi {name}, thanks for signing up. Confirm your email address to finish setting up your account.",
      "button": "Verify email",
      "footer": "If you did not create an account, you can safely ignore this email."
    },
    "changeEmailConfirmation": {
      "subject": "Confirm your new email address",
      "preview": "Confirm your email change for SaaSy Land",
      "heading": "Confirm email change",
      "body": "Hi {name}, we received a request to change your email address to {newEmail}. Click the button below to confirm this change.",
      "button": "Confirm email change",
      "footer": "If you did not request this change, you can safely ignore this email."
    }
  },
  "auth": {
    "oAuth": {
      "google": "Sign in with Google",
      "github": "Sign in with GitHub",
      "success": "Signed in successfully!"
    },
    "errors": {
      "accessDenied": "Access denied.",
      "accountNotFound": "Account not found.",
      "credentialAccountNotFound": "Credential account not found.",
      "emailCanNotBeUpdated": "Email cannot be updated.",
      "emailNotVerified": "Email not verified.",
      "failedToCreateSession": "Failed to create session.",
      "failedToCreateUser": "Failed to create user.",
      "failedToGetSession": "Failed to get session.",
      "failedToGetUserInfo": "Failed to get user info.",
      "failedToUnlinkLastAccount": "Failed to unlink last account.",
      "failedToUpdateUser": "Failed to update user.",
      "idTokenNotSupported": "ID token not supported.",
      "invalidEmail": "Invalid email.",
      "invalidEmailOrPassword": "Invalid email or password.",
      "invitationNotFound": "Invitation not found.",
      "invalidPassword": "Invalid password.",
      "invalidToken": "Invalid token.",
      "passwordTooLong": "Password is too long.",
      "passwordTooShort": "Password is too short.",
      "providerNotFound": "Provider not found.",
      "sessionExpired": "Session expired.",
      "socialAccountAlreadyLinked": "Social account already linked.",
      "unknownError": "An unknown error occurred.",
      "userAlreadyExists": "User already exists.",
      "userAlreadyExistsUseAnotherEmail": "User already exists. Use another email.",
      "userAlreadyHasPassword": "User already has a password. Provide that to delete the account.",
      "userEmailNotFound": "User email not found.",
      "userNotFound": "User not found."
    },
    "validations": {
      "emailRequired": "Email is required.",
      "emailInvalid": "Please enter a valid email address.",
      "emailMaxLength": "Email cannot be longer than {max} characters.",
      "nameRequired": "Name is required.",
      "nameMaxLength": "Name cannot be longer than {max} characters.",
      "passwordRequired": "Password is required.",
      "passwordMinLength": "Password must be at least {min} characters long.",
      "passwordMaxLength": "Password cannot be longer than {max} characters.",
      "passwordUppercase": "Password must contain at least one uppercase letter.",
      "passwordSpecialCharacter": "Password must contain at least one special character.",
      "confirmPasswordRequired": "Please confirm your password.",
      "passwordsMustMatch": "Passwords must match.",
      "atLeastMinCharactersLong": "At least {min} characters long",
      "atLeastOneSpecialCharacter": "At least one special character",
      "atLeastOneUppercase": "At least one uppercase letter"
    },
    "layout": {
      "backToHome": "Back to Home"
    },
    "signInPage": {
      "metadata": {
        "title": "Sign In",
        "description": "Sign in to your account at {name}."
      },
      "form": {
        "title": "Welcome back",
        "description": "Enter your details to sign in to your account.",
        "email": "Email",
        "password": "Password",
        "submit": "Continue",
        "submitting": "Signing In...",
        "success": "Signed in successfully!",
        "error": "Invalid email or password. Please try again.",
        "noAccount": "Don't have an account? <signup>Sign up</signup>",
        "forgotPassword": "Forgot password?",
        "continueWithGithub": "Continue with GitHub",
        "continueWithGoogle": "Continue with Google",
        "or": "or"
      }
    },
    "signUpPage": {
      "metadata": {
        "title": "Sign Up",
        "description": "Sign up for an account at {name}."
      },
      "form": {
        "title": "Sign Up",
        "description": "Sign up for an account at {name}.",
        "name": "Name",
        "email": "Email",
        "password": "Password",
        "submit": "Continue",
        "submitting": "Signing Up...",
        "success": "Account created successfully!",
        "error": "An error occurred during sign up. Please try again.",
        "hasAccount": "Already have an account? <signin>Sign in</signin>",
        "or": "or",
        "confirmPassword": "Confirm password",
        "termsAndPrivacy": "By signing up, you agree to our <terms>Terms of Service</terms> and <privacy>Privacy Policy</privacy>."
      }
    },
    "forgotPasswordPage": {
      "metadata": {
        "title": "Forgot Password",
        "description": "Request a password reset link for your {name} account."
      },
      "form": {
        "title": "Forgot your password?",
        "description": "Enter your email and we will send you a reset link if an account exists.",
        "email": "Email",
        "submit": "Send reset link",
        "submitting": "Sending...",
        "success": "If an account exists for that email, check your inbox for a reset link.",
        "error": "Something went wrong. Please try again.",
        "rememberPassword": "Remember your password? <signin>Sign in</signin>"
      }
    },
    "resetPasswordPage": {
      "metadata": {
        "title": "Reset Password",
        "description": "Choose a new password for your {name} account."
      },
      "form": {
        "title": "Choose a new password",
        "description": "Enter and confirm your new password below.",
        "password": "New password",
        "confirmPassword": "Confirm new password",
        "submit": "Update password",
        "submitting": "Updating...",
        "success": "Your password has been updated. You can sign in now.",
        "error": "This reset link is invalid or has expired. Please request a new one.",
        "invalidToken": "This reset link is invalid or has expired.",
        "requestNewLink": "Request a new reset link"
      }
    }
  },
  "blogPage": {
    "metadata": {
      "title": "Blog",
      "description": "Notes and updates from SaaSy Land."
    },
    "nav": {
      "docs": "Docs",
      "blog": "Blog"
    },
    "index": {
      "title": "Blog",
      "description": "Markdown posts compiled with Fumadocs MDX."
    },
    "post": {
      "backToBlog": "Back to blog",
      "writtenBy": "Written by",
      "dateLabel": "Published"
    }
  },
  "admin": {
    "page": {
      "metadata": {
        "description": "Signed-in app area."
      },
      "welcome": "App — {name}"
    },
    "components": {
      "userWidget": {
        "signedInAs": "Signed in as <user>{name}</user>"
      },
      "signOutButton": {
        "signOut": "Sign Out",
        "signingOut": "Signing out...",
        "success": "See you later!"
      }
    },
    "payments": {
      "metadata": {
        "title": "Payments",
        "description": "Manage revenue, transactions, and payout settings."
      },
      "title": "Payments",
      "description": "Manage revenue, transactions, and payout settings.",
      "actions": {
        "export": "Export",
        "settings": "Payment Settings"
      },
      "tabs": {
        "transactions": "Transactions",
        "subscriptions": "Subscriptions",
        "payouts": "Payouts",
        "refunds": "Refunds"
      },
      "stats": {
        "refunded": {
          "title": "Refunded (30d)",
          "value": "$1,240.00",
          "trend": "-12.4%"
        },
        "refundRate": {
          "title": "Refund Rate",
          "value": "1.2%",
          "trend": "-0.2%"
        },
        "pending": {
          "title": "Pending Approvals",
          "subtitle": "Amounting to $407.00",
          "value": "3"
        },
        "vsLastMonth": "vs last month"
      },
      "table": {
        "title": "Recent Refunds",
        "columns": {
          "customer": "Customer",
          "amount": "Amount",
          "item": "Original Item",
          "reason": "Reason",
          "date": "Date",
          "status": "Status"
        },
        "pagination": {
          "showing": "Showing 1 to 4 of 24 results",
          "previous": "Previous",
          "next": "Next",
          "page1": "1",
          "page2": "2",
          "ellipsis": "..."
        },
        "rows": [
          {
            "id": 1,
            "initials": "AJ",
            "name": "Alex Johnson",
            "email": "alex@example.com",
            "amount": "$199.00",
            "type": "Full refund",
            "item": "Pro Annual",
            "reason": "Accidental renewal",
            "date": "Nov 25, 2024",
            "status": "Processed",
            "statusColor": "bg-emerald-500",
            "statusTextColor": "text-muted-foreground"
          },
          {
            "id": 2,
            "initials": "SS",
            "name": "Sarah Smith",
            "email": "sarah.s@domain.com",
            "amount": "$9.50",
            "type": "Partial refund",
            "item": "Pro Monthly",
            "reason": "Downtime compensation",
            "date": "Nov 22, 2024",
            "status": "Processed",
            "statusColor": "bg-emerald-500",
            "statusTextColor": "text-muted-foreground"
          },
          {
            "id": 3,
            "initials": "MB",
            "name": "Michael Brown",
            "email": "mike.b@startup.io",
            "amount": "$9.00",
            "type": "Full refund",
            "item": "Starter Monthly",
            "reason": "Not a fit",
            "date": "Nov 20, 2024",
            "status": "Pending",
            "statusColor": "bg-amber-500",
            "statusTextColor": "text-amber-500 dark:text-amber-400"
          },
          {
            "id": 4,
            "initials": "ED",
            "name": "Emma Davis",
            "email": "emma@design.co",
            "amount": "$199.00",
            "type": "Full refund",
            "item": "Pro Annual",
            "reason": "Fraudulent charge",
            "date": "Nov 18, 2024",
            "status": "Failed",
            "statusColor": "bg-rose-500",
            "statusTextColor": "text-rose-500 dark:text-rose-400"
          }
        ]
      }
    },
    "sidebar": {
      "title": "SaaSy Land",
      "version": "v2.0.0",
      "groups": {
        "overview": "Overview",
        "offerings": "Offerings",
        "administration": "Administration",
        "content": "Content"
      },
      "links": {
        "dashboard": "Dashboard",
        "analytics": "Analytics",
        "products": "Products",
        "courses": "Courses",
        "pricingModels": "Pricing Models",
        "contentAccess": "Content & Access",
        "userManagement": "User Management",
        "activeSessions": "Active Sessions",
        "payments": "Payments & Billing",
        "settings": "Settings",
        "blog": "Blog",
        "landingPage": "Landing Page"
      },
      "logo": "SL",
      "badges": {
        "activeSessionsBadge": "3"
      }
    },
    "dashboard": {
      "title": "Overview",
      "description": "Welcome back, here is what is happening today.",
      "actions": {
        "last30Days": "Last 30 Days",
        "addProduct": "Add Product"
      },
      "stats": {
        "revenue": {
          "title": "Total Revenue (MRR)",
          "value": "$24,500.00",
          "trend": "+12.5%"
        },
        "activeUsers": {
          "title": "Active Users",
          "value": "1,248",
          "trend": "+4.2%"
        },
        "currentSessions": {
          "title": "Current Sessions",
          "value": "42",
          "badge": "Active Now"
        },
        "churnRate": {
          "title": "Churn Rate",
          "value": "1.2%",
          "trend": "-0.8%"
        }
      },
      "chart": {
        "title": "Revenue Overview",
        "description": "Monthly recurring revenue over the last 12 months",
        "filters": {
          "12m": "12M",
          "30d": "30D",
          "7d": "7D"
        },
        "yAxis": ["$30k", "$20k", "$10k", "$0"],
        "xAxis": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
      },
      "users": {
        "title": "User Management",
        "description": "Manage your team members and their account permissions here.",
        "search": "Filter users...",
        "filters": {
          "role": "Role",
          "status": "Status"
        },
        "export": "Export",
        "table": {
          "columns": {
            "user": "User",
            "role": "Role",
            "status": "Status",
            "lastActive": "Last Active",
            "actions": "Actions"
          },
          "pagination": {
            "showing": "Showing 1 to 3 of 42 entries",
            "previous": "Previous",
            "next": "Next"
          },
          "rows": [
            {
              "id": 1,
              "name": "Sarah Jenkins",
              "email": "sarah@example.com",
              "avatar": "https://i.pravatar.cc/150?u=1",
              "role": "Admin",
              "status": "Online",
              "lastActive": "Just now"
            },
            {
              "id": 2,
              "name": "Michael Ross",
              "email": "michael@example.com",
              "initials": "MR",
              "role": "Editor",
              "status": "Offline",
              "lastActive": "2 hours ago"
            },
            {
              "id": 3,
              "name": "Elena Smith",
              "email": "elena@example.com",
              "avatar": "https://i.pravatar.cc/150?u=4",
              "role": "Viewer",
              "status": "Idle",
              "lastActive": "15 mins ago"
            }
          ]
        }
      },
      "sessions": {
        "title": "Active Sessions",
        "revoke": "Revoke",
        "signoutAll": "Sign out all other sessions",
        "current": "Current",
        "items": [
          {
            "id": 1,
            "device": "Mac OS • Safari",
            "location": "New York, US • IP: 192.168.1.1",
            "icon": "laptop",
            "isCurrent": true
          },
          {
            "id": 2,
            "device": "iOS • Chrome",
            "location": "London, UK • 2 hours ago",
            "icon": "smartphone",
            "isCurrent": false
          }
        ]
      },
      "security": {
        "title": "Security Settings",
        "mfa": "Two-Factor Auth",
        "mfaDesc": "Require 2FA for all users",
        "email": "Email Notifications",
        "emailDesc": "Daily summary reports"
      }
    },
    "courses": {
      "create": {
        "title": "Create Course",
        "actions": {
          "cancel": "Cancel",
          "save": "Save Course"
        },
        "sections": {
          "general": {
            "title": "General Information",
            "name": {
              "label": "Course Title",
              "placeholder": "e.g. Advanced UI Design Patterns..."
            },
            "description": {
              "label": "Description",
              "placeholder": "Briefly describe what students will learn...",
              "help": "Will be displayed on the course landing page."
            }
          },
          "curriculum": {
            "title": "Curriculum",
            "description": "Structure your course into sections and lessons.",
            "expandAll": "Expand All",
            "addSection": "Add New Section",
            "addLesson": "Add Lesson"
          },
          "pricing": {
            "title": "Pricing & Access",
            "model": {
              "label": "Billing Model",
              "oneTime": "One-time Purchase",
              "subscription": "Subscription"
            },
            "price": {
              "label": "Price",
              "placeholder": "0.00"
            },
            "duration": {
              "label": "Access Duration",
              "lifetime": "Lifetime Access"
            }
          },
          "status": {
            "title": "Status",
            "publish": {
              "label": "Publish Course",
              "description": "Make it visible to students"
            },
            "certificate": {
              "label": "Issue Certificate",
              "description": "Upon 100% completion"
            }
          },
          "media": {
            "title": "Course Thumbnail",
            "upload": "Upload image",
            "help": "1920x1080px recommended"
          },
          "organization": {
            "title": "Organization",
            "category": {
              "label": "Category",
              "placeholder": "Select category..."
            },
            "difficulty": {
              "label": "Difficulty Level",
              "placeholder": "e.g. Beginner, Advanced..."
            }
          }
        }
      }
    },
    "settings": {
      "metadata": {
        "title": "Settings | SaaSy Land",
        "description": "Manage your workspace preferences, security, and billing."
      },
      "title": "Settings",
      "description": "Manage your workspace preferences, security, and billing.",
      "tabs": {
        "general": "General",
        "security": "Security",
        "team": "Team & Members",
        "billing": "Billing",
        "integrations": "Integrations",
        "api": "API Keys"
      },
      "profile": {
        "title": "Workspace Profile",
        "description": "Update your workspace identity and details.",
        "uploadImage": "Upload image",
        "removeImage": "Remove",
        "imageHint": "Recommended size: 256x256px. Max 2MB.",
        "workspaceName": "Workspace Name",
        "supportEmail": "Support Email",
        "workspaceUrl": "Workspace URL",
        "urlHint": "This is your unique URL to log in to your dashboard.",
        "saveChanges": "Save Changes",
        "urlPrefix": "app.saasyland.com/"
      },
      "preferences": {
        "title": "Preferences",
        "description": "Configure regional and language settings for your workspace.",
        "language": "Language",
        "timezone": "Timezone",
        "languages": {
          "en": "English (US)",
          "es": "Español",
          "fr": "Français"
        },
        "timezones": {
          "utc": "UTC (Coordinated Universal Time)",
          "est": "EST (Eastern Standard Time)",
          "pst": "PST (Pacific Standard Time)"
        },
        "announcements": {
          "title": "Feature Announcements",
          "description": "Receive emails about new features and updates."
        }
      },
      "dangerZone": {
        "title": "Danger Zone",
        "description": "Irreversible actions for your workspace.",
        "delete": {
          "title": "Delete Workspace",
          "description": "Permanently delete this workspace and all of its data. This action cannot be undone.",
          "button": "Delete Workspace"
        }
      },
      "security": {
        "password": {
          "title": "Change Password",
          "description": "Update your password to keep your account secure.",
          "current": "Current Password",
          "new": "New Password",
          "confirm": "Confirm New Password",
          "requirements": {
            "title": "Password requirements",
            "length": "Minimum 8 characters long",
            "case": "At least one uppercase and lowercase letter",
            "special": "At least one number or special character"
          },
          "update": "Update Password"
        },
        "twoFactor": {
          "title": "Two-Factor Authentication (2FA)",
          "description": "Add an extra layer of security to your account.",
          "app": "Authenticator App",
          "appDescription": "Use an app like Google Authenticator or 1Password to generate time-based codes.",
          "enable": "Enable 2FA"
        },
        "sessions": {
          "title": "Active Sessions",
          "description": "Manage devices that are currently logged into your account.",
          "logoutAll": "Log out all other devices",
          "currentBadge": "Current session",
          "revoke": "Revoke",
          "activeAgo": "Active {time} ago",
          "list": [
            {
              "device": "Mac OS Safari",
              "location": "New York, USA",
              "ip": "192.168.1.1",
              "isCurrent": true,
              "icon": "laptop"
            },
            {
              "device": "iOS Chrome",
              "location": "London, UK",
              "time": "2 hours",
              "isCurrent": false,
              "icon": "smartphone"
            }
          ],
          "separator": " • "
        }
      }
    },
    "analytics": {
      "metadata": {
        "title": "Analytics | SaaSy Land",
        "description": "Monitor your SaaS performance, revenue, and user engagement."
      },
      "title": "Analytics Overview",
      "description": "Monitor your SaaS performance, revenue, and user engagement.",
      "actions": {
        "datePicker": "Last 30 Days"
      },
      "tabs": {
        "overview": "Overview",
        "revenue": "Revenue",
        "audience": "Audience",
        "retention": "Retention",
        "reports": "Reports"
      },
      "kpi": {
        "mrr": {
          "title": "Total MRR",
          "value": "$124,500",
          "trend": "14.2%",
          "trendLabel": "vs last month"
        },
        "activeUsers": {
          "title": "Active Users",
          "value": "45,231",
          "trend": "5.4%",
          "trendLabel": "vs last month"
        },
        "churn": {
          "title": "Churn Rate",
          "value": "1.2%",
          "trend": "0.4%",
          "trendLabel": "vs last month"
        },
        "arpu": {
          "title": "Avg. Revenue Per User",
          "value": "$42.50",
          "trend": "2.1%",
          "trendLabel": "vs last month"
        }
      },
      "chart": {
        "title": "Revenue Overview",
        "description": "Daily revenue generated over the last 30 days.",
        "legend": {
          "new": "New Subscriptions",
          "renewals": "Renewals"
        },
        "tooltip": "{date}: {value}",
        "activeTooltip": "Today: {value}"
      },
      "regions": {
        "title": "Top Regions",
        "viewAll": "View All",
        "list": [
          {
            "name": "United States",
            "flag": "🇺🇸",
            "percentage": 45
          },
          {
            "name": "United Kingdom",
            "flag": "🇬🇧",
            "percentage": 22
          },
          {
            "name": "Canada",
            "flag": "🇨🇦",
            "percentage": 15
          },
          {
            "name": "Germany",
            "flag": "🇩🇪",
            "percentage": 8
          },
          {
            "name": "Australia",
            "flag": "🇦🇺",
            "percentage": 10
          }
        ]
      },
      "upgrades": {
        "title": "Recent Upgrades",
        "viewAll": "View All",
        "list": [
          {
            "initials": "AS",
            "name": "Alice Smith",
            "action": "Upgraded to Pro Plan",
            "time": "2 mins ago",
            "colors": "from-blue-600 to-indigo-400"
          },
          {
            "initials": "MJ",
            "name": "Michael Johnson",
            "action": "Upgraded to Enterprise",
            "time": "1 hour ago",
            "colors": "from-emerald-600 to-teal-400"
          },
          {
            "initials": "ER",
            "name": "Emma Richards",
            "action": "Upgraded to Pro Plan",
            "time": "3 hours ago",
            "colors": "from-rose-600 to-orange-400"
          },
          {
            "initials": "DL",
            "name": "David Lee",
            "action": "Upgraded to Team Plan",
            "time": "5 hours ago",
            "colors": "border border-border/50 bg-secondary text-muted-foreground"
          },
          {
            "initials": "SK",
            "name": "Sarah Kline",
            "action": "Upgraded to Pro Plan",
            "time": "1 day ago",
            "colors": "from-purple-600 to-fuchsia-400"
          }
        ]
      }
    },
    "users": {
      "metadata": {
        "title": "User Management | SaaSy Land",
        "description": "Manage your team members, permissions, and customer accounts."
      },
      "title": "User Management",
      "description": "Manage your team members, permissions, and customer accounts.",
      "actions": {
        "export": "Export",
        "addUser": "Add User"
      },
      "search": {
        "placeholder": "Search users by name, email, or ID..."
      },
      "filters": {
        "role": "Role: All",
        "status": "Status: Active"
      },
      "tabs": {
        "allUsers": "All Users",
        "invitations": "Invitations",
        "roles": "Roles & Permissions",
        "security": "Security"
      },
      "table": {
        "headers": {
          "user": "User",
          "role": "Role",
          "status": "Status",
          "lastActive": "Last Active"
        }
      },
      "pagination": {
        "info": "Showing <highlight>{start}</highlight> to <highlight>{end}</highlight> of <highlight>{total}</highlight> results"
      },
      "list": [
        {
          "id": "u1",
          "name": "Alice Smith",
          "email": "alice.smith@example.com",
          "initials": "AS",
          "colors": "from-blue-600 to-indigo-400",
          "role": "Administrator",
          "status": "Active",
          "statusColor": "emerald",
          "lastActive": "Just now"
        },
        {
          "id": "u2",
          "name": "Michael Johnson",
          "email": "m.johnson@example.com",
          "avatar": "https://i.pravatar.cc/150?u=a042581f4e29026704d",
          "role": "Editor",
          "status": "Active",
          "statusColor": "emerald",
          "lastActive": "2 hours ago"
        },
        {
          "id": "u3",
          "name": "Emma Richards",
          "email": "emma.r@example.com",
          "initials": "ER",
          "colors": "from-rose-600 to-orange-400",
          "role": "Viewer",
          "status": "Pending",
          "statusColor": "amber",
          "lastActive": "Never"
        },
        {
          "id": "u4",
          "name": "David Lee",
          "email": "david.lee@example.com",
          "avatar": "https://i.pravatar.cc/150?u=a042581f4e29026024d",
          "isBanned": true,
          "role": "Subscriber",
          "status": "Banned",
          "statusColor": "rose",
          "lastActive": "Oct 12, 2023"
        },
        {
          "id": "u5",
          "name": "Sarah Kline",
          "email": "s.kline@example.com",
          "initials": "SK",
          "colors": "from-purple-600 to-fuchsia-400",
          "role": "Editor",
          "status": "Active",
          "statusColor": "emerald",
          "lastActive": "1 day ago"
        }
      ],
      "invitations": {
        "title": "Invitations",
        "description": "Manage pending team invitations and access links.",
        "actions": {
          "copyLink": "Copy Link",
          "sendInvite": "Send Invite"
        },
        "search": {
          "placeholder": "Search invites by email..."
        },
        "filters": {
          "role": "Role: All",
          "status": "Status: Pending"
        },
        "table": {
          "headers": {
            "email": "Email",
            "role": "Role",
            "status": "Status",
            "sentDate": "Sent Date"
          }
        },
        "pagination": {
          "info": "Showing <highlight>{start}</highlight> to <highlight>{end}</highlight> of <highlight>{total}</highlight> results"
        },
        "list": [
          {
            "id": "i1",
            "email": "alex.chen@example.com",
            "invitedBy": "John Doe",
            "role": "Administrator",
            "status": "Pending",
            "statusColor": "amber",
            "sentDate": "2 hours ago"
          },
          {
            "id": "i2",
            "email": "m.roberts@startup.io",
            "invitedBy": "John Doe",
            "role": "Viewer",
            "status": "Pending",
            "statusColor": "amber",
            "sentDate": "Yesterday"
          },
          {
            "id": "i3",
            "email": "k.williams@acme.co",
            "invitedBy": "Sarah Kline",
            "role": "Editor",
            "status": "Expired",
            "statusColor": "rose",
            "sentDate": "Oct 10, 2023"
          },
          {
            "id": "i4",
            "email": "j.miller@example.com",
            "invitedBy": "John Doe",
            "role": "Subscriber",
            "status": "Pending",
            "statusColor": "amber",
            "sentDate": "Oct 20, 2023"
          },
          {
            "id": "i5",
            "email": "s.taylor@designco.com",
            "invitedBy": "John Doe",
            "role": "Editor",
            "status": "Expired",
            "statusColor": "rose",
            "sentDate": "Sep 28, 2023"
          }
        ]
      },
      "roles": {
        "title": "Roles & Permissions",
        "description": "Define access levels and manage permissions across your organization.",
        "actions": {
          "createRole": "Create Role"
        },
        "search": {
          "placeholder": "Search roles by name or description..."
        },
        "filters": {
          "type": "Type: All"
        },
        "table": {
          "headers": {
            "name": "Role Name",
            "description": "Description",
            "type": "Type",
            "users": "Users"
          }
        },
        "pagination": {
          "info": "Showing <highlight>{start}</highlight> to <highlight>{end}</highlight> of <highlight>{total}</highlight> roles"
        },
        "list": [
          {
            "id": "r1",
            "name": "Administrator",
            "description": "Full access to all system features, billing, and settings.",
            "type": "System",
            "typeColor": "default",
            "usersCount": "3 users",
            "icon": "Shield",
            "iconColor": "default"
          },
          {
            "id": "r2",
            "name": "Editor",
            "description": "Can edit products and content, but cannot manage users.",
            "type": "System",
            "typeColor": "default",
            "usersCount": "12 users",
            "icon": "Pen",
            "iconColor": "default"
          },
          {
            "id": "r3",
            "name": "Support Agent",
            "description": "Access to user sessions and basic troubleshooting tools.",
            "type": "Custom",
            "typeColor": "fuchsia",
            "usersCount": "5 users",
            "icon": "HelpCircle",
            "iconColor": "fuchsia"
          },
          {
            "id": "r4",
            "name": "Viewer",
            "description": "Read-only access to analytics and dashboards.",
            "type": "System",
            "typeColor": "default",
            "usersCount": "28 users",
            "icon": "Eye",
            "iconColor": "default"
          },
          {
            "id": "r5",
            "name": "API Developer",
            "description": "Access to developer settings, API keys, and webhooks.",
            "type": "Custom",
            "typeColor": "fuchsia",
            "usersCount": "2 users",
            "icon": "Code",
            "iconColor": "fuchsia"
          }
        ]
      }
    },
    "products": {
      "metadata": {
        "title": "Products | SaaSy Land",
        "description": "Manage physical merchandise, digital downloads, and protected content subscriptions."
      },
      "tabs": {
        "all": "All Products",
        "onetime": "One-time Purchases",
        "subscriptions": "Subscriptions",
        "drafts": "Drafts",
        "categories": "Categories",
        "collections": "Collections",
        "courses": "Courses"
      },
      "title": "Products",
      "description": "Manage physical merchandise, digital downloads, and protected content subscriptions.",
      "actions": {
        "create": "Create Product"
      },
      "search": {
        "placeholder": "Search products by name or SKU..."
      },
      "filters": {
        "type": "Type: All",
        "status": "Status: Active",
        "category": "Category",
        "collection": "Collection",
        "cycle": "Cycle",
        "model": "Model",
        "visibility": "Visibility",
        "sortby": "Sort by"
      },
      "table": {
        "headers": {
          "product": "Product",
          "type": "Type",
          "pricing": "Pricing",
          "status": "Status",
          "metrics": "Metrics"
        }
      },
      "pagination": {
        "info": "Showing <highlight>{start}</highlight> to <highlight>{end}</highlight> of <highlight>{total}</highlight> products"
      },
      "list": [
        {
          "id": "p1",
          "name": "Mastering Next.js Course",
          "description": "85 video lessons • Protected access",
          "type": "Subscription",
          "price": "$49.00",
          "billingCycle": "/ mo",
          "status": "Active",
          "statusColor": "emerald",
          "metrics": "1,248 active",
          "icon": "Video",
          "iconColor": "fuchsia"
        },
        {
          "id": "p2",
          "name": "UI/UX Design Handbook",
          "description": "PDF & ePub formats",
          "type": "Digital",
          "price": "$29.00",
          "billingCycle": "one-time",
          "status": "Active",
          "statusColor": "emerald",
          "metrics": "3,402 sales",
          "icon": "Book",
          "iconColor": "default"
        },
        {
          "id": "p3",
          "name": "SaaSy Land Signature Tee",
          "description": "Apparel • Multiple variants",
          "type": "Physical",
          "price": "$35.00",
          "billingCycle": "one-time",
          "status": "Draft",
          "statusColor": "neutral",
          "metrics": "0 sales",
          "icon": "Shirt",
          "iconColor": "default"
        },
        {
          "id": "p4",
          "name": "Premium Creator Community",
          "description": "Discord access & weekly calls",
          "type": "Subscription",
          "price": "$19.00",
          "billingCycle": "/ mo",
          "status": "Active",
          "statusColor": "emerald",
          "metrics": "890 active",
          "icon": "Users",
          "iconColor": "fuchsia"
        }
      ],
      "onetime": {
        "title": "One-time Purchases",
        "description": "Manage individual products, digital downloads, and physical merchandise.",
        "list": [
          {
            "id": "ot1",
            "name": "UI/UX Design Handbook",
            "description": "PDF & ePub formats",
            "type": "Digital",
            "price": "$29.00",
            "billingCycle": "one-time",
            "status": "Active",
            "statusColor": "emerald",
            "metrics": "3,402 sales",
            "icon": "Book",
            "iconColor": "default",
            "tags": [
              {
                "icon": "Folder",
                "text": "Ebooks",
                "color": "default"
              },
              {
                "icon": "Bookmark",
                "text": "Best Sellers",
                "color": "fuchsia"
              }
            ]
          },
          {
            "id": "ot2",
            "name": "Freelance Starter Kit",
            "description": "Notion templates & assets",
            "type": "Digital",
            "price": "$49.00",
            "billingCycle": "one-time",
            "status": "Active",
            "statusColor": "emerald",
            "metrics": "1,120 sales",
            "icon": "Layers",
            "iconColor": "fuchsia",
            "tags": [
              {
                "icon": "Folder",
                "text": "Templates",
                "color": "default"
              },
              {
                "icon": "Bookmark",
                "text": "Featured",
                "color": "blue"
              }
            ]
          },
          {
            "id": "ot3",
            "name": "SaaSy Land Signature Tee",
            "description": "Apparel • Multiple variants",
            "type": "Physical",
            "price": "$35.00",
            "billingCycle": "one-time",
            "status": "Draft",
            "statusColor": "neutral",
            "metrics": "0 sales",
            "icon": "Shirt",
            "iconColor": "default",
            "tags": [
              {
                "icon": "Folder",
                "text": "Apparel",
                "color": "default"
              },
              {
                "icon": "Bookmark",
                "text": "Summer Drop",
                "color": "emerald"
              }
            ]
          }
        ]
      },
      "subscriptions": {
        "title": "Subscriptions",
        "description": "Manage recurring billing plans, membership tiers, and usage-based pricing.",
        "table": {
          "headers": {
            "product": "Plan Name",
            "model": "Model",
            "pricing": "Pricing",
            "status": "Status",
            "metrics": "Metrics"
          }
        },
        "list": [
          {
            "id": "sub-1",
            "name": "Pro Membership",
            "description": "Unlimited access & premium features",
            "type": "Recurring",
            "price": "$29.00",
            "billingCycle": "/ month",
            "status": "Active",
            "statusColor": "emerald",
            "metrics": "1,204 active",
            "icon": "Crown",
            "iconColor": "fuchsia",
            "tags": [
              {
                "icon": "Folder",
                "text": "SaaS Tier",
                "color": "default"
              },
              {
                "icon": "Star",
                "text": "Most Popular",
                "color": "fuchsia"
              }
            ]
          },
          {
            "id": "sub-2",
            "name": "Team Workspace",
            "description": "Up to 10 seats & shared resources",
            "type": "Recurring",
            "price": "$290.00",
            "billingCycle": "/ year",
            "status": "Active",
            "statusColor": "emerald",
            "metrics": "342 active",
            "icon": "Users",
            "iconColor": "default",
            "tags": [
              {
                "icon": "Folder",
                "text": "B2B",
                "color": "default"
              },
              {
                "icon": "Building2",
                "text": "Business",
                "color": "blue"
              }
            ]
          },
          {
            "id": "sub-3",
            "name": "Developer API Access",
            "description": "Metered endpoints & webhook integrations",
            "type": "Usage-based",
            "price": "$0.05",
            "billingCycle": "/ 1k req",
            "status": "Active",
            "statusColor": "emerald",
            "metrics": "89 active",
            "icon": "Server",
            "iconColor": "emerald",
            "tags": [
              {
                "icon": "Folder",
                "text": "Add-ons",
                "color": "default"
              },
              {
                "icon": "Code",
                "text": "Developer",
                "color": "emerald"
              }
            ]
          }
        ]
      },
      "categories": {
        "title": "Categories",
        "description": "Organize your products, subscription plans, and digital goods.",
        "table": {
          "headers": {
            "category": "Category",
            "visibility": "Visibility",
            "items": "Items",
            "lastUpdated": "Last Updated"
          }
        },
        "list": [
          {
            "id": "cat-1",
            "name": "SaaS Plans",
            "description": "Core subscription tiers for standard users",
            "visibility": "Public",
            "visibilityStatus": "public",
            "items": "12",
            "lastUpdated": "Oct 24, 2023",
            "icon": "FolderOpen"
          },
          {
            "id": "cat-2",
            "name": "Add-ons & Extras",
            "description": "One-time extensions and API limits",
            "visibility": "Public",
            "visibilityStatus": "public",
            "items": "8",
            "lastUpdated": "Sep 12, 2023",
            "icon": "Puzzle"
          },
          {
            "id": "cat-3",
            "name": "Legacy Plans",
            "description": "Grandfathered plans no longer available for purchase",
            "visibility": "Hidden",
            "visibilityStatus": "hidden",
            "items": "3",
            "lastUpdated": "Jan 05, 2023",
            "icon": "Archive"
          }
        ]
      },
      "collections": {
        "title": "Collections",
        "description": "Curate and group your products, subscription plans, and digital goods.",
        "table": {
          "headers": {
            "collection": "Collection",
            "visibility": "Visibility",
            "items": "Items",
            "lastUpdated": "Last Updated"
          }
        },
        "list": [
          {
            "id": "col-1",
            "name": "SaaS Plans",
            "description": "Core subscription tiers for standard users",
            "visibility": "Public",
            "visibilityStatus": "public",
            "items": "12",
            "lastUpdated": "Oct 24, 2023",
            "icon": "FolderOpen"
          },
          {
            "id": "col-2",
            "name": "Add-ons & Extras",
            "description": "One-time extensions and API limits",
            "visibility": "Public",
            "visibilityStatus": "public",
            "items": "8",
            "lastUpdated": "Sep 12, 2023",
            "icon": "Puzzle"
          },
          {
            "id": "col-3",
            "name": "Legacy Plans",
            "description": "Grandfathered plans no longer available for purchase",
            "visibility": "Hidden",
            "visibilityStatus": "hidden",
            "items": "3",
            "lastUpdated": "Jan 05, 2023",
            "icon": "Archive"
          }
        ]
      },
      "create": {
        "title": "Create Product",
        "actions": {
          "cancel": "Cancel",
          "save": "Save Product"
        },
        "sections": {
          "general": {
            "title": "General Information",
            "name": {
              "label": "Product Name",
              "placeholder": "e.g. Pro Plan, E-book..."
            },
            "description": {
              "label": "Description",
              "placeholder": "Briefly describe what this product includes...",
              "help": "Will be displayed on checkout and customer portal pages."
            }
          },
          "pricing": {
            "title": "Pricing & Billing",
            "model": {
              "label": "Billing Model",
              "subscription": "Subscription",
              "oneTime": "One-time"
            },
            "price": {
              "label": "Price",
              "placeholder": "0.00"
            },
            "period": {
              "label": "Billing Period",
              "monthly": "Monthly"
            }
          },
          "media": {
            "title": "Media & Images",
            "upload": "Click to upload or drag and drop",
            "help": "SVG, PNG, JPG or GIF (max. 800x400px)"
          },
          "status": {
            "title": "Status",
            "publish": {
              "label": "Publish Product",
              "description": "Make it visible to customers"
            },
            "requireLogin": {
              "label": "Require Login",
              "description": "User must be authenticated"
            }
          },
          "organization": {
            "title": "Organization",
            "category": {
              "label": "Category",
              "placeholder": "Select category..."
            },
            "collection": {
              "label": "Collection",
              "placeholder": "Add to collection..."
            }
          }
        }
      }
    },
    "pricingModels": {
      "title": "Pricing Models",
      "description": "Manage subscription tiers and one-time payment options.",
      "actions": {
        "allTypes": "All Types",
        "createModel": "Create Model"
      },
      "stats": {
        "monthlyRecurring": "Monthly Recurring",
        "activeSubscribers": "Active Subscribers",
        "activeModels": "Active Models"
      },
      "tags": {
        "subscription": "Subscription",
        "oneTime": "One-Time",
        "mostPopular": "Most Popular"
      },
      "models": {
        "monthly": {
          "title": "Monthly Pass",
          "price": "$29",
          "interval": "/ month",
          "description": "Billed monthly. Cancel anytime."
        },
        "annual": {
          "title": "Annual Pass",
          "price": "$290",
          "interval": "/ year",
          "description": "Save $58 compared to monthly."
        },
        "lifetime": {
          "title": "Course License",
          "price": "$99",
          "interval": "/ lifetime",
          "description": "Standard pricing for standalone items."
        }
      },
      "labels": {
        "includedAccess": "Included Access",
        "activeUsers": "{count} active",
        "inactive": "Inactive",
        "editModel": "Edit Model",
        "moreOptions": "More Options",
        "deleteModel": "Delete Model",
        "toggleStatus": "Toggle Status"
      },
      "features": {
        "allCourses": "All currently published courses",
        "discord": "Exclusive community Discord",
        "qa": "Monthly live Q&A sessions",
        "everythingInMonthly": "Everything in Monthly Pass",
        "sourceFiles": "Downloadable source files",
        "portfolioReview": "1-on-1 yearly portfolio review",
        "standaloneCourse": "Selected standalone course",
        "lifetimeUpdates": "Lifetime updates for material",
        "guarantee": "30-day money-back guarantee"
      }
    },
    "blog": {
      "title": "Publications",
      "description": "Create, manage, and analyze your blog content.",
      "actions": {
        "categories": "Categories",
        "writePost": "Write Post",
        "loadMore": "Load More Articles"
      },
      "stats": {
        "totalViews": "Total Views (30d)",
        "subscribers": "Subscribers",
        "publishedPosts": "Published Posts",
        "draftsPending": "{count} drafts pending"
      },
      "filters": {
        "all": "All Posts",
        "published": "Published",
        "drafts": "Drafts",
        "scheduled": "Scheduled",
        "search": "Search articles..."
      },
      "badges": {
        "published": "Published",
        "draft": "Draft",
        "scheduled": "Scheduled"
      },
      "meta": {
        "readTime": "{minutes} min read",
        "publishedOn": "{date}",
        "lastEdited": "Last edited {time} ago",
        "publishesTomorrow": "Publishes tomorrow"
      },
      "labels": {
        "gridView": "Grid View",
        "tableView": "Table View",
        "moreOptions": "More Options"
      },
      "table": {
        "postDetails": "Post Details",
        "status": "Status",
        "category": "Category",
        "author": "Author",
        "date": "Date",
        "views": "Views",
        "actions": "Actions"
      },
      "pagination": {
        "info": "Showing <highlight>{start}</highlight> to <highlight>{end}</highlight> of <highlight>{total}</highlight> posts"
      },
      "create": {
        "title": "Write Post",
        "description": "Create a new markdown blog post with advanced settings.",
        "actions": {
          "preview": "Preview",
          "saveDraft": "Save Draft",
          "publish": "Publish"
        },
        "editor": {
          "title": "Post Title",
          "titlePlaceholder": "Enter post title here...",
          "slug": "URL Slug",
          "slugPlaceholder": "post-title-here",
          "contentPlaceholder": "Write your post content here... You can use Markdown.",
          "fullscreen": "Fullscreen"
        },
        "settings": {
          "featuredImage": "Featured Image",
          "upload": "Click to upload",
          "uploadHelp": "SVG, PNG, JPG or GIF (max. 5MB)",
          "publishing": "Publishing",
          "status": "Status",
          "statusDraft": "Draft",
          "statusPublished": "Published",
          "statusScheduled": "Scheduled",
          "category": "Category",
          "categorySelect": "Select Category",
          "categoryUpdates": "Product Updates",
          "categoryTutorials": "Tutorials",
          "categoryCompany": "Company News",
          "tags": "Tags",
          "tagsPlaceholder": "Add tags separated by commas...",
          "excerpt": "Excerpt",
          "excerptPlaceholder": "Brief summary of the post..."
        }
      }
    },
    "landingPage": {
      "title": "Landing Page Editor",
      "description": "Design and customize your landing page visually.",
      "actions": {
        "preview": "Preview",
        "saveChanges": "Save Changes",
        "publish": "Publish"
      },
      "sidebar": {
        "addSection": "Add Section",
        "sections": {
          "hero": "Hero Section",
          "features": "Features Grid",
          "video": "Video Showcase",
          "testimonials": "Testimonials",
          "pricing": "Pricing Table",
          "gallery": "Image Gallery",
          "faq": "FAQ Accordion",
          "contact": "Contact Form"
        }
      },
      "canvas": {
        "newRelease": "New v2.0 Release",
        "supercharge": "Supercharge Your ",
        "growth": "SaaS Growth",
        "description": "The all-in-one platform to manage your customers, billing, and content. Build faster, convert better.",
        "getStarted": "Get Started Free",
        "bookDemo": "Book a Demo",
        "addSectionHere": "Add Section Here",
        "featuresHeading": "Powerful Features",
        "featuresSubheading": "Everything you need to scale your business.",
        "feature1": "Analytics",
        "feature2": "Security",
        "feature3": "Team Sync"
      },
      "properties": {
        "title": "Section Properties",
        "description": "Customize the selected element",
        "layout": "Alignment",
        "spacing": "Spacing",
        "paddingTop": "Padding Top",
        "paddingBot": "Padding Bot",
        "background": "Background Style",
        "content": "Content",
        "generateAI": "Generate AI",
        "badgeText": "Badge Text",
        "heading": "Heading",
        "subheading": "Subheading",
        "buttonActions": "Actions",
        "primaryButton": "Primary Button",
        "secondaryButton": "Secondary Button",
        "label": "Label"
      }
    }
  },
  "appPage": {
    "title": "App Page",
    "description": "Welcome to the App page."
  }
};
export default messages;