ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Abidjan';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Accra';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Addis_Ababa';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Algiers';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Asmara';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Bamako';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Bangui';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Banjul';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Bissau';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Blantyre';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Brazzaville';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Bujumbura';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Cairo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Casablanca';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Ceuta';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Conakry';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Dakar';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Dar_es_Salaam';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Djibouti';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Douala';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/El_Aaiun';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Freetown';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Gaborone';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Harare';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Johannesburg';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Juba';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Kampala';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Khartoum';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Kigali';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Kinshasa';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Lagos';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Libreville';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Lome';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Luanda';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Lubumbashi';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Lusaka';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Malabo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Maputo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Maseru';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Mbabane';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Mogadishu';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Monrovia';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Nairobi';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Ndjamena';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Niamey';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Nouakchott';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Ouagadougou';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Porto-Novo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Sao_Tome';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Tripoli';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Tunis';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Africa/Windhoek';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Anchorage';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Anguilla';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Antigua';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Araguaina';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Argentina/Buenos_Aires';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Argentina/Cordoba';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Argentina/Mendoza';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Asuncion';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Bahia';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Barbados';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Belem';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Belize';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Boa_Vista';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Bogota';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Boise';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Campo_Grande';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Cancun';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Caracas';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Cayenne';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Chicago';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Chihuahua';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Costa_Rica';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Cuiaba';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Denver';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Detroit';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Edmonton';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/El_Salvador';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Fortaleza';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Guatemala';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Guayaquil';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Guyana';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Halifax';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Havana';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Jamaica';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/La_Paz';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Lima';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Managua';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Manaus';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Mexico_City';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Monterrey';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Montevideo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Panama';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Paramaribo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Phoenix';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Port-au-Prince';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Puerto_Rico';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Regina';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Santiago';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Santo_Domingo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Sao_Paulo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Tijuana';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Toronto';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'America/Vancouver';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Almaty';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Amman';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Ashgabat';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Baghdad';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Baku';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Bangkok';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Beirut';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Bishkek';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Colombo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Damascus';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Dhaka';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Dubai';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Dushanbe';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Hong_Kong';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Ho_Chi_Minh';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Jakarta';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Jerusalem';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Kabul';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Karachi';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Kathmandu';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Kolkata';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Kuala_Lumpur';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Kuwait';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Macau';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Manila';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Muscat';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Nicosia';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Qatar';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Riyadh';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Seoul';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Shanghai';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Singapore';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Taipei';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Tashkent';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Tbilisi';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Tehran';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Tokyo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Ulaanbaatar';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Vladivostok';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Asia/Yerevan';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Adelaide';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Brisbane';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Darwin';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Hobart';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Melbourne';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Perth';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Australia/Sydney';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Amsterdam';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Andorra';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Athens';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Belgrade';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Berlin';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Bratislava';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Brussels';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Bucharest';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Budapest';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Chisinau';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Copenhagen';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Dublin';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Helsinki';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Istanbul';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Kiev';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Lisbon';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Ljubljana';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/London';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Luxembourg';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Madrid';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Malta';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Minsk';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Monaco';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Moscow';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Oslo';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Paris';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Prague';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Riga';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Rome';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Sofia';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Stockholm';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Tallinn';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Vienna';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Vilnius';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Warsaw';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Europe/Zurich';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Pacific/Auckland';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Pacific/Fiji';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Pacific/Guam';--> statement-breakpoint
ALTER TYPE "public"."user_timezone" ADD VALUE IF NOT EXISTS 'Pacific/Honolulu';
