#!/usr/bin/env bun

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const SERVER_ONLY_NAMESPACES = ["emails"] as const
import { I18N } from "~/src/integrations/use-intl/i18n.config"

import { getLocaleMessagesDir, loadLocaleMessagesFromDir } from "./i18n-messages"

const MESSAGES_DIR = getLocaleMessagesDir()
const SOURCE_LOCALE = I18N.DEFAULT_LOCALE
const MESSAGE_TYPES_PATH = join(import.meta.dirname, "../src/integrations/use-intl/en-US.d.json.ts")

function compareAlphabetically(a: string, b: string): number {
  return a.localeCompare(b)
}

function flattenMessageKeys(value: unknown, prefix = ""): string[] {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return prefix.length > 0 ? [prefix] : []
  }

  return Object.entries(value as Record<string, unknown>).flatMap(([key, nested]) => {
    const path = prefix.length > 0 ? `${prefix}.${key}` : key

    if (nested !== null && typeof nested === "object" && !Array.isArray(nested)) {
      return flattenMessageKeys(nested, path)
    }

    return [path]
  })
}

function loadLocaleKeys(locale: string): Set<string> {
  const messages = loadLocaleMessagesFromDir(locale, MESSAGES_DIR)
  return new Set(flattenMessageKeys(messages))
}

function writeMessageTypes(): void {
  const messages = loadLocaleMessagesFromDir(SOURCE_LOCALE, MESSAGES_DIR)
  const declaration = `// Auto-generated by check:i18n. Do not edit.\n\ndeclare const messages: ${JSON.stringify(messages, null, 2).trim()};\nexport default messages;\n`
  writeFileSync(MESSAGE_TYPES_PATH, declaration, "utf8")
}

function checkLocaleParity(): boolean {
  const sourceKeys = loadLocaleKeys(SOURCE_LOCALE)
  const problems: string[] = []

  for (const locale of I18N.SUPPORTED_LOCALES) {
    if (locale === SOURCE_LOCALE) {
      continue
    }

    const localeKeys = loadLocaleKeys(locale)
    const missing = [...sourceKeys].filter((key) => !localeKeys.has(key)).toSorted(compareAlphabetically)
    const extra = [...localeKeys].filter((key) => !sourceKeys.has(key)).toSorted(compareAlphabetically)

    if (missing.length === 0 && extra.length === 0) {
      continue
    }

    problems.push(`Locale "${locale}" is out of sync with "${SOURCE_LOCALE}":`)

    for (const key of missing) {
      problems.push(`  missing: ${key}`)
    }

    for (const key of extra) {
      problems.push(`  extra: ${key}`)
    }
  }

  if (problems.length === 0) {
    process.stdout.write(`✅ Translation keys are in sync across ${I18N.SUPPORTED_LOCALES.join(", ")}.\n`)
    return true
  }

  process.stderr.write("\n❌ Translation locale parity check failed.\n\n")
  process.stderr.write(`${problems.join("\n")}\n\n`)
  process.stderr.write(`Update ${MESSAGES_DIR}/{locale}/*.json so every locale matches ${SOURCE_LOCALE} keys exactly.\n\n`)
  return false
}

const SOURCE_ROOT = join(import.meta.dirname, "../src")
const UNIQUE_BINDING = 1

function collectSourceFiles(dir: string, found: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)

    if (entry.isDirectory()) {
      collectSourceFiles(path, found)
    } else if (path.endsWith(".ts") || path.endsWith(".tsx")) {
      found.push(path)
    }
  }

  return found
}

/**
 * The root layout withholds `SERVER_ONLY_NAMESPACES` from the client message payload.
 * A Client Component that reads a key under one of them would resolve to nothing at
 * runtime, so fail the build here instead.
 */
function checkClientNamespaces(): boolean {
  const violations: string[] = []

  for (const file of collectSourceFiles(SOURCE_ROOT)) {
    const source = readFileSync(file, "utf8")

    if (file.includes("/__test__/") || !file.includes("/presentation/components/")) {
      continue
    }

    const keys = [
      ...source.matchAll(/useTranslations\("(?<namespace>[^"]+)"\)/gu),
      ...source.matchAll(/\bt(?:\.rich)?\("(?<namespace>[^"]+)"/gu),
      ...source.matchAll(/namespace="(?<namespace>[^"]+)"/gu),
    ].flatMap((match) => (match.groups?.["namespace"] === undefined ? [] : [match.groups["namespace"]]))

    for (const key of keys) {
      const excluded = SERVER_ONLY_NAMESPACES.find((namespace) => key === namespace || key.startsWith(`${namespace}.`))

      if (excluded !== undefined) {
        violations.push(`  ${file.replace(SOURCE_ROOT, "src")}: reads "${key}" from server-only namespace "${excluded}"`)
      }
    }
  }

  if (violations.length === 0) {
    process.stdout.write(`✅ No browser component reads an email namespace.\n`)
    return true
  }

  process.stderr.write("\n❌ Client Component reads a namespace withheld from the client payload.\n\n")
  process.stderr.write(`${violations.join("\n")}\n\n`)
  process.stderr.write("Keep email translations in the email integration.\n\n")
  return false
}

/**
 * Resolve every literal `t("key")` call back to its namespace and confirm the key exists.
 *
 * use-intl's `IntlMessages` augmentation does not make `t()` key-safe, so a typo or a
 * key that was never added survives typecheck and only fails at runtime with
 * MISSING_MESSAGE. Dynamic keys (template literals, variables) are skipped.
 */
function checkMessageKeys(): boolean {
  const known = loadLocaleKeys(SOURCE_LOCALE)
  const problems: string[] = []

  for (const file of collectSourceFiles(SOURCE_ROOT)) {
    const source = readFileSync(file, "utf8")

    // `const t = useTranslations("ns")` / `const t = await getTranslations("ns")`
    const namespacesByBinding = new Map<string, Set<string>>()

    for (const match of source.matchAll(
      /(?:const|let)\s+(?<binding>\w+)\s*=\s*(?:await\s+)?(?:useTranslations|getTranslations)\(\s*"(?<namespace>[^"]+)"\s*\)/gu,
    )) {
      const { binding, namespace } = match.groups ?? {}

      if (binding !== undefined && namespace !== undefined) {
        const seen = namespacesByBinding.get(binding) ?? new Set<string>()
        seen.add(namespace)
        namespacesByBinding.set(binding, seen)
      }
    }

    // A file can bind the same name to different namespaces in sibling components. This
    // scan has no scope analysis, so resolving those would report the wrong namespace —
    // skip them rather than emit a false positive.
    const bindings = new Map<string, string>()

    for (const [binding, namespaces] of namespacesByBinding) {
      const [only] = [...namespaces]

      if (namespaces.size === UNIQUE_BINDING && only !== undefined) {
        bindings.set(binding, only)
      }
    }

    for (const [binding, namespace] of bindings) {
      const calls = new RegExp(String.raw`\b${binding}(?:\.rich|\.markup)?\(\s*"(?<key>[^"]+)"`, "gu")

      for (const call of source.matchAll(calls)) {
        const key = call.groups?.["key"]

        if (key === undefined) {
          continue
        }

        const fullKey = `${namespace}.${key}`

        if (!known.has(fullKey)) {
          problems.push(`  ${file.replace(SOURCE_ROOT, "src")}: "${fullKey}" is not defined in ${SOURCE_LOCALE}`)
        }
      }
    }
  }

  if (problems.length === 0) {
    process.stdout.write("\u2705 Every literal message key resolves.\n")
    return true
  }

  process.stderr.write("\n\u274c Message keys used in code are missing from the catalog.\n\n")
  process.stderr.write(`${problems.join("\n")}\n\n`)
  return false
}

function run(): void {
  writeMessageTypes()

  if (!checkLocaleParity() || !checkClientNamespaces() || !checkMessageKeys()) {
    process.exit(1)
  }
}

run()
