#!/usr/bin/env bun

import { readdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { AbstractIntlMessages } from "use-intl"

const SERVER_ONLY_NAMESPACES = ["emails"] as const
import { I18N } from "~/src/integrations/use-intl/i18n.config"

import { loadLocaleMessages } from "./i18n-messages"

const SOURCE_LOCALE = I18N.DEFAULT_LOCALE
const MESSAGE_TYPES_PATH = join(import.meta.dirname, "../src/integrations/use-intl/en-US.d.json.ts")

function compareAlphabetically(a: string, b: string): number {
  return a.localeCompare(b)
}

function flattenMessageKeys(value: unknown, prefix = ""): string[] {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    return prefix.length > 0 ? [prefix] : []
  }

  return Object.entries(value).flatMap(([key, nested]) => {
    const path = prefix.length > 0 ? `${prefix}.${key}` : key

    if (nested !== null && typeof nested === "object" && !Array.isArray(nested)) {
      return flattenMessageKeys(nested, path)
    }

    return [path]
  })
}

function loadLocaleKeys(locale: string): Set<string> {
  const messages = loadLocaleMessages(locale)
  return new Set(flattenMessageKeys(messages))
}

function messageShape(messages: AbstractIntlMessages): string {
  return `{${Object.entries(messages)
    .map(([key, value]) => `${JSON.stringify(key)}: ${typeof value === "string" ? "string" : messageShape(value)}`)
    .join(";\n")}}`
}

function writeMessageTypes(): void {
  const messages = loadLocaleMessages(SOURCE_LOCALE)
  const declaration = `// Auto-generated by check:i18n. Do not edit.\n\ndeclare const messages: ${messageShape(messages)};\nexport default messages;\n`
  writeFileSync(MESSAGE_TYPES_PATH, declaration, "utf8")
  const validationKeys = flattenMessageKeys(messages).filter((key) => key.includes(".validations."))
  const validationKeyArray = validationKeys.length === 0
    ? "[]"
    : `[\n${validationKeys.map((key) => `  ${JSON.stringify(key)},`).join("\n")}\n]`
  writeFileSync(
    join(import.meta.dirname, "../src/integrations/use-intl/validation-keys.ts"),
    `// Auto-generated by check:i18n. Do not edit.\nexport const VALIDATION_MESSAGE_KEYS = ${validationKeyArray} as const\n`,
    "utf8",
  )
}

function checkLocaleParity(): boolean {
  const sourceKeys = loadLocaleKeys(SOURCE_LOCALE)
  const problems: string[] = []

  for (const locale of I18N.SUPPORTED_LOCALES) {
    if (locale === SOURCE_LOCALE) {
      continue
    }

    const localeKeys = loadLocaleKeys(locale)
    const missing = [...sourceKeys].filter((key) => !localeKeys.has(key)).toSorted(compareAlphabetically)
    const extra = [...localeKeys].filter((key) => !sourceKeys.has(key)).toSorted(compareAlphabetically)

    if (missing.length === 0 && extra.length === 0) {
      continue
    }

    problems.push(`Locale "${locale}" is out of sync with "${SOURCE_LOCALE}":`)

    for (const key of missing) {
      problems.push(`  missing: ${key}`)
    }

    for (const key of extra) {
      problems.push(`  extra: ${key}`)
    }
  }

  if (problems.length === 0) {
    process.stdout.write(`✅ Translation keys are in sync across ${I18N.SUPPORTED_LOCALES.join(", ")}.\n`)
    return true
  }

  process.stderr.write("\n❌ Translation locale parity check failed.\n\n")
  process.stderr.write(`${problems.join("\n")}\n\n`)
  process.stderr.write(`Update messages/{locale}/*.json so every locale matches ${SOURCE_LOCALE} keys exactly.\n\n`)
  return false
}

const SOURCE_ROOT = join(import.meta.dirname, "../src")

function collectSourceFiles(dir: string, found: string[] = []): string[] {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name)

    if (entry.isDirectory()) {
      collectSourceFiles(path, found)
    } else if (path.endsWith(".ts") || path.endsWith(".tsx")) {
      found.push(path)
    }
  }

  return found
}

function checkClientNamespaces(): boolean {
  const violations: string[] = []

  for (const file of collectSourceFiles(SOURCE_ROOT)) {
    const source = readFileSync(file, "utf8")

    if (file.includes("/__test__/") || !file.includes("/presentation/components/")) {
      continue
    }

    const keys = [
      ...source.matchAll(/useTranslations\("(?<namespace>[^"]+)"\)/gu),
      ...source.matchAll(/\bt(?:\.rich)?\("(?<namespace>[^"]+)"/gu),
      ...source.matchAll(/namespace="(?<namespace>[^"]+)"/gu),
    ].flatMap((match) => (match.groups?.["namespace"] === undefined ? [] : [match.groups["namespace"]]))

    for (const key of keys) {
      const excluded = SERVER_ONLY_NAMESPACES.find((namespace) => key === namespace || key.startsWith(`${namespace}.`))

      if (excluded !== undefined) {
        violations.push(`  ${file.replace(SOURCE_ROOT, "src")}: reads "${key}" from server-only namespace "${excluded}"`)
      }
    }
  }

  if (violations.length === 0) {
    process.stdout.write(`✅ No browser component reads an email namespace.\n`)
    return true
  }

  process.stderr.write("\n❌ Client Component reads a namespace withheld from the client payload.\n\n")
  process.stderr.write(`${violations.join("\n")}\n\n`)
  process.stderr.write("Keep email translations in the email integration.\n\n")
  return false
}

function run(): void {
  writeMessageTypes()
  process.stdout.write("✅ Generated message-key types for the compiler.\n")

  if (!checkLocaleParity() || !checkClientNamespaces()) {
    process.exit(1)
  }
}

run()
