import type { JSX } from "react"
import reactPackage from "react/package.json"

import { useQuery } from "@tanstack/react-query"
import { useFormatter, useTranslations } from "use-intl/react"

import { starCountQuery } from "~/src/integrations/github/github.queries"

import { Skeleton } from "~/src/presentation/components/shadcn/skeleton"

import { HighlightGroup, HighlightItem } from "~/src/presentation/components/custom/landing-page/components/hover-highlight"

/**
 * The ten numbers the rest of the page has to earn.
 *
 * Every figure here is generated by the repository being sold, and the Record section further
 * down says where to find each one. That is the reason the band can exist at all: a row of big
 * numbers on a landing page is decoration unless the page also tells you how to check them.
 *
 * Drawn with `gap-px` over a hairline-coloured ground rather than with per-cell borders. A grid
 * that reflows from five columns to two would otherwise need a different set of border rules at
 * each breakpoint, and one of them would always be wrong.
 */
const FACT_KEYS = ["coverage", "tests", "locales", "components", "mau", "stars", "upkeep", "types", "tables", "admin"] as const

const MAJOR = 0

/**
 * Read from the installed runtime, not typed into a message file: a version written by hand rots
 * the week after the next release and nobody notices. React rather than the framework, because the
 * CLI writes either Next or TanStack Start and both sit on this.
 */
const REACT_MAJOR = `React ${reactPackage.version.split(".")[MAJOR]}`

export const ProofSection = (): JSX.Element => {
  const t = useTranslations("pages.landing.proof")
  const format = useFormatter()
  const { data: stars } = useQuery(starCountQuery)

  /** The two figures the repository reports for itself. Everything else is a translated constant. */
  const measured = {
    stars: typeof stars === "number" ? format.number(stars) : <Skeleton aria-hidden className="h-7 w-16" />,
    upkeep: REACT_MAJOR,
  }

  return (
    <section className="relative border-t border-border">
      <div className="mx-auto w-full max-w-7xl">
        <HighlightGroup className="grid grid-cols-2 gap-px bg-border md:grid-cols-5" element="dl" name="proof-highlight">
          {FACT_KEYS.map((key) => (
            <HighlightItem className="bg-background" contentClassName="px-6 py-8 md:px-8 md:py-10" id={key} key={key}>
              {/* `break-words`: the cell is half a phone wide, and a compound noun in a language
                  that builds them — German "Benutzeroberflächenkomponenten" — has no space to
                  wrap at, so without this the label pushes the whole document into a sideways
                  scroll. */}
              <dt className="font-mono text-label break-words text-muted-foreground uppercase">{t(`facts.${key}.label`)}</dt>
              <dd className="mt-3 text-[1.75rem] leading-none font-semibold tracking-[-0.035em] text-foreground tabular-nums">
                {key === "stars" || key === "upkeep" ? measured[key] : t(`facts.${key}.value`)}
              </dd>
              <dd className="mt-2 text-body-sm text-pretty text-muted-foreground">{t(`facts.${key}.note`)}</dd>
            </HighlightItem>
          ))}
        </HighlightGroup>
      </div>
    </section>
  )
}
