import type { JSX } from "react"

import { getTranslations } from "next-intl/server"

/**
 * The five numbers the rest of the page has to earn.
 *
 * Every figure here is generated by the repository being sold, and the Record section further
 * down says where to find each one. That is the reason the band can exist at all: a row of big
 * numbers on a landing page is decoration unless the page also tells you how to check them.
 *
 * Drawn with `gap-px` over a hairline-coloured ground rather than with per-cell borders. A grid
 * that reflows from five columns to two would otherwise need a different set of border rules at
 * each breakpoint, and one of them would always be wrong.
 */
const FACT_KEYS = ["coverage", "tests", "locales", "components", "mau"] as const

export async function ProofSection(): Promise<JSX.Element> {
  const t = await getTranslations("pages.landing.proof")

  return (
    <section className="relative border-t border-border">
      <div className="mx-auto w-full max-w-7xl">
        <dl className="grid grid-cols-2 gap-px bg-border md:grid-cols-5">
          {FACT_KEYS.map((key) => (
            // Five facts in a two-column grid leaves a hole, and the hole shows the hairline
            // ground the gaps are painted on. The last cell spans the row instead.
            <div className="bg-background px-6 py-8 last:col-span-2 md:px-8 md:py-10 md:last:col-span-1" key={key}>
              <dt className="font-mono text-label text-muted-foreground uppercase">{t(`facts.${key}.label`)}</dt>
              <dd className="mt-3 text-[1.75rem] leading-none font-semibold tracking-[-0.035em] text-foreground tabular-nums">
                {t(`facts.${key}.value`)}
              </dd>
              <dd className="mt-2 text-body-sm text-pretty text-muted-foreground">{t(`facts.${key}.note`)}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  )
}
