import { cacheLife } from "next/cache"
import type { JSX } from "react"
import reactPackage from "react/package.json"

import { getTranslations } from "next-intl/server"

import { HighlightGroup, HighlightItem } from "~/src/app/[locale]/(landing)/_components/shared/hover-highlight"

/**
 * The ten numbers the rest of the page has to earn.
 *
 * Every figure here is generated by the repository being sold, and the Record section further
 * down says where to find each one. That is the reason the band can exist at all: a row of big
 * numbers on a landing page is decoration unless the page also tells you how to check them.
 *
 * Drawn with `gap-px` over a hairline-coloured ground rather than with per-cell borders. A grid
 * that reflows from five columns to two would otherwise need a different set of border rules at
 * each breakpoint, and one of them would always be wrong.
 */
const FACT_KEYS = ["coverage", "tests", "locales", "components", "mau", "stars", "upkeep", "types", "tables", "admin"] as const

const MAJOR = 0

/**
 * Read from the installed runtime, not typed into a message file: a version written by hand rots
 * the week after the next release and nobody notices. React rather than the framework, because the
 * CLI writes either Next or TanStack Start and both sit on this.
 */
const REACT_MAJOR = `React ${reactPackage.version.split(".")[MAJOR]}`

const STARS_REPOSITORY = "pjborowiecki/saasyland.com"

/** Shown when GitHub is unreachable or rate-limits the build, so the tile never renders a zero. */
const STARS_FALLBACK = 435

function isStarPayload(value: unknown): value is { stargazers_count: number } {
  return typeof value === "object" && value !== null && typeof (value as { stargazers_count?: unknown }).stargazers_count === "number"
}

async function getStarCount(): Promise<number> {
  "use cache"
  cacheLife("hours")

  try {
    const response = await fetch(`https://api.github.com/repos/${STARS_REPOSITORY}`, {
      headers: { accept: "application/vnd.github+json" },
    })
    if (!response.ok) {
      return STARS_FALLBACK
    }
    const payload: unknown = await response.json()
    return isStarPayload(payload) ? payload.stargazers_count : STARS_FALLBACK
  } catch {
    return STARS_FALLBACK
  }
}

export async function ProofSection(): Promise<JSX.Element> {
  const [t, stars] = await Promise.all([getTranslations("pages.landing.proof"), getStarCount()])

  /** The two figures the repository reports for itself. Everything else is a translated constant. */
  const measured: Partial<Record<(typeof FACT_KEYS)[number], string>> = {
    stars: stars.toLocaleString("en-US"),
    upkeep: REACT_MAJOR,
  }

  return (
    <section className="relative border-t border-border">
      <div className="mx-auto w-full max-w-7xl">
        <HighlightGroup className="grid grid-cols-2 gap-px bg-border md:grid-cols-5" element="dl" name="proof-highlight">
          {FACT_KEYS.map((key) => (
            <HighlightItem className="bg-background" contentClassName="px-6 py-8 md:px-8 md:py-10" id={key} key={key}>
              <dt className="font-mono text-label text-muted-foreground uppercase">{t(`facts.${key}.label`)}</dt>
              <dd className="mt-3 text-[1.75rem] leading-none font-semibold tracking-[-0.035em] text-foreground tabular-nums">
                {measured[key] ?? t(`facts.${key}.value`)}
              </dd>
              <dd className="mt-2 text-body-sm text-pretty text-muted-foreground">{t(`facts.${key}.note`)}</dd>
            </HighlightItem>
          ))}
        </HighlightGroup>
      </div>
    </section>
  )
}
