export const ROUTES = {
  ADMIN: "/admin",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_BLOG: "/admin/blog",
  ADMIN_CONTENT: "/admin/content-access",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_LANDING_PAGE: "/admin/landing-page",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_PRICING: "/admin/pricing-models",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_SESSIONS: "/admin/sessions",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_USERS: "/admin/users",
  API_AUTH: {
    REQUEST_PASSWORD_RESET: "/request-password-reset",
    RESET_PASSWORD: "/reset-password",
    SIGN_IN_EMAIL: "/sign-in/email",
    SIGN_UP_EMAIL: "/sign-up/email",
  },
  APP: "/app",
  AUTH_CALLBACK: "/auth/callback",
  FORGOT_PASSWORD: "/auth/forgot-password",
  HOME: "/",
  PRIVACY: "/privacy",
  RESET_PASSWORD: "/auth/reset-password",
  SIGN_IN: "/auth/sign-in",
  SIGN_UP: "/auth/sign-up",
  TERMS: "/terms",
  TWO_FACTOR: "/auth/two-factor",
  VERIFY_EMAIL: "/auth/verify-email",
} as const
