/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as LandingIndexRouteImport } from './routes/_landing.index'
import { Route as LandingLicenceRouteImport } from './routes/_landing.licence'
import { Route as LandingPremiumRouteImport } from './routes/_landing.premium'
import { Route as LandingPrivacyRouteImport } from './routes/_landing.privacy'
import { Route as LandingRefundsRouteImport } from './routes/_landing.refunds'
import { Route as LandingTermsRouteImport } from './routes/_landing.terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminLandingPageRouteImport } from './routes/admin.landing-page'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPricingModelsRouteImport } from './routes/admin.pricing-models'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppLicenseRouteImport } from './routes/app.license'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthTwoFactorRouteImport } from './routes/auth.two-factor'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSplatRouteImport } from './routes/blog.$'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as LandingNewsletterConfirmRouteImport } from './routes/_landing.newsletter.confirm'
import { Route as LandingNewsletterUnsubscribeRouteImport } from './routes/_landing.newsletter.unsubscribe'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBlogCreateRouteImport } from './routes/admin.blog.create'
import { Route as AdminCoursesCreateRouteImport } from './routes/admin.courses.create'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsCreateRouteImport } from './routes/admin.products.create'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersAllRouteImport } from './routes/admin.users.all'
import { Route as AdminUsersInvitationsRouteImport } from './routes/admin.users.invitations'
import { Route as AdminUsersRolesRouteImport } from './routes/admin.users.roles'
import { Route as AdminUsersSecurityRouteImport } from './routes/admin.users.security'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingLicenceRoute = LandingLicenceRouteImport.update({
  id: '/licence',
  path: '/licence',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPremiumRoute = LandingPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingRefundsRoute = LandingRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => LandingRoute,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LandingRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLandingPageRoute = AdminLandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingModelsRoute = AdminPricingModelsRouteImport.update({
  id: '/pricing-models',
  path: '/pricing-models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLicenseRoute = AppLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTwoFactorRoute = AuthTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BlogRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DocsRoute,
} as any)
const LandingNewsletterConfirmRoute =
  LandingNewsletterConfirmRouteImport.update({
    id: '/newsletter/confirm',
    path: '/newsletter/confirm',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingNewsletterUnsubscribeRoute =
  LandingNewsletterUnsubscribeRouteImport.update({
    id: '/newsletter/unsubscribe',
    path: '/newsletter/unsubscribe',
    getParentRoute: () => LandingRoute,
  } as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogCreateRoute = AdminBlogCreateRouteImport.update({
  id: '/blog/create',
  path: '/blog/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesCreateRoute = AdminCoursesCreateRouteImport.update({
  id: '/courses/create',
  path: '/courses/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersAllRoute = AdminUsersAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersInvitationsRoute = AdminUsersInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersRolesRoute = AdminUsersRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersSecurityRoute = AdminUsersSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/licence': typeof LandingLicenceRoute
  '/premium': typeof LandingPremiumRoute
  '/privacy': typeof LandingPrivacyRoute
  '/refunds': typeof LandingRefundsRoute
  '/terms': typeof LandingTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/landing-page': typeof AdminLandingPageRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing-models': typeof AdminPricingModelsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/app/license': typeof AppLicenseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/newsletter/confirm': typeof LandingNewsletterConfirmRoute
  '/newsletter/unsubscribe': typeof LandingNewsletterUnsubscribeRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/users/all': typeof AdminUsersAllRoute
  '/admin/users/invitations': typeof AdminUsersInvitationsRoute
  '/admin/users/roles': typeof AdminUsersRolesRoute
  '/admin/users/security': typeof AdminUsersSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/licence': typeof LandingLicenceRoute
  '/premium': typeof LandingPremiumRoute
  '/privacy': typeof LandingPrivacyRoute
  '/refunds': typeof LandingRefundsRoute
  '/terms': typeof LandingTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/landing-page': typeof AdminLandingPageRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing-models': typeof AdminPricingModelsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/search': typeof ApiSearchRoute
  '/app/license': typeof AppLicenseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/': typeof LandingIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api': typeof ApiIndexRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/newsletter/confirm': typeof LandingNewsletterConfirmRoute
  '/newsletter/unsubscribe': typeof LandingNewsletterUnsubscribeRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/users/all': typeof AdminUsersAllRoute
  '/admin/users/invitations': typeof AdminUsersInvitationsRoute
  '/admin/users/roles': typeof AdminUsersRolesRoute
  '/admin/users/security': typeof AdminUsersSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/_landing/licence': typeof LandingLicenceRoute
  '/_landing/premium': typeof LandingPremiumRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/_landing/refunds': typeof LandingRefundsRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/landing-page': typeof AdminLandingPageRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing-models': typeof AdminPricingModelsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/app/license': typeof AppLicenseRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/two-factor': typeof AuthTwoFactorRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/blog/$': typeof BlogSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/_landing/': typeof LandingIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_landing/newsletter/confirm': typeof LandingNewsletterConfirmRoute
  '/_landing/newsletter/unsubscribe': typeof LandingNewsletterUnsubscribeRoute
  '/admin/blog/create': typeof AdminBlogCreateRoute
  '/admin/courses/create': typeof AdminCoursesCreateRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/users/all': typeof AdminUsersAllRoute
  '/admin/users/invitations': typeof AdminUsersInvitationsRoute
  '/admin/users/roles': typeof AdminUsersRolesRoute
  '/admin/users/security': typeof AdminUsersSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/blog'
    | '/docs'
    | '/licence'
    | '/premium'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/admin/analytics'
    | '/admin/landing-page'
    | '/admin/payments'
    | '/admin/pricing-models'
    | '/admin/settings'
    | '/admin/users'
    | '/api/search'
    | '/app/license'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/auth/verify-email'
    | '/blog/$'
    | '/docs/$'
    | '/admin/'
    | '/api/'
    | '/app/'
    | '/blog/'
    | '/docs/'
    | '/newsletter/confirm'
    | '/newsletter/unsubscribe'
    | '/admin/blog/create'
    | '/admin/courses/create'
    | '/admin/products/create'
    | '/admin/users/all'
    | '/admin/users/invitations'
    | '/admin/users/roles'
    | '/admin/users/security'
    | '/api/auth/$'
    | '/admin/blog/'
    | '/admin/products/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/licence'
    | '/premium'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/admin/analytics'
    | '/admin/landing-page'
    | '/admin/payments'
    | '/admin/pricing-models'
    | '/admin/settings'
    | '/api/search'
    | '/app/license'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/auth/verify-email'
    | '/blog/$'
    | '/docs/$'
    | '/'
    | '/admin'
    | '/api'
    | '/app'
    | '/blog'
    | '/docs'
    | '/newsletter/confirm'
    | '/newsletter/unsubscribe'
    | '/admin/blog/create'
    | '/admin/courses/create'
    | '/admin/products/create'
    | '/admin/users/all'
    | '/admin/users/invitations'
    | '/admin/users/roles'
    | '/admin/users/security'
    | '/api/auth/$'
    | '/admin/blog'
    | '/admin/products'
    | '/admin/users'
  id:
    | '__root__'
    | '/_landing'
    | '/admin'
    | '/app'
    | '/auth'
    | '/blog'
    | '/docs'
    | '/_landing/licence'
    | '/_landing/premium'
    | '/_landing/privacy'
    | '/_landing/refunds'
    | '/_landing/terms'
    | '/admin/analytics'
    | '/admin/landing-page'
    | '/admin/payments'
    | '/admin/pricing-models'
    | '/admin/settings'
    | '/admin/users'
    | '/api/search'
    | '/app/license'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/two-factor'
    | '/auth/verify-email'
    | '/blog/$'
    | '/docs/$'
    | '/_landing/'
    | '/admin/'
    | '/api/'
    | '/app/'
    | '/blog/'
    | '/docs/'
    | '/_landing/newsletter/confirm'
    | '/_landing/newsletter/unsubscribe'
    | '/admin/blog/create'
    | '/admin/courses/create'
    | '/admin/products/create'
    | '/admin/users/all'
    | '/admin/users/invitations'
    | '/admin/users/roles'
    | '/admin/users/security'
    | '/api/auth/$'
    | '/admin/blog/'
    | '/admin/products/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
  ApiIndexRoute: typeof ApiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/licence': {
      id: '/_landing/licence'
      path: '/licence'
      fullPath: '/licence'
      preLoaderRoute: typeof LandingLicenceRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/premium': {
      id: '/_landing/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof LandingPremiumRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/refunds': {
      id: '/_landing/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof LandingRefundsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/landing-page': {
      id: '/admin/landing-page'
      path: '/landing-page'
      fullPath: '/admin/landing-page'
      preLoaderRoute: typeof AdminLandingPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing-models': {
      id: '/admin/pricing-models'
      path: '/pricing-models'
      fullPath: '/admin/pricing-models'
      preLoaderRoute: typeof AdminPricingModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/license': {
      id: '/app/license'
      path: '/license'
      fullPath: '/app/license'
      preLoaderRoute: typeof AppLicenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/two-factor': {
      id: '/auth/two-factor'
      path: '/two-factor'
      fullPath: '/auth/two-factor'
      preLoaderRoute: typeof AuthTwoFactorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof BlogRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_landing/newsletter/confirm': {
      id: '/_landing/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof LandingNewsletterConfirmRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/newsletter/unsubscribe': {
      id: '/_landing/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof LandingNewsletterUnsubscribeRouteImport
      parentRoute: typeof LandingRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/create': {
      id: '/admin/blog/create'
      path: '/blog/create'
      fullPath: '/admin/blog/create'
      preLoaderRoute: typeof AdminBlogCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/create': {
      id: '/admin/courses/create'
      path: '/courses/create'
      fullPath: '/admin/courses/create'
      preLoaderRoute: typeof AdminCoursesCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/all': {
      id: '/admin/users/all'
      path: '/all'
      fullPath: '/admin/users/all'
      preLoaderRoute: typeof AdminUsersAllRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/invitations': {
      id: '/admin/users/invitations'
      path: '/invitations'
      fullPath: '/admin/users/invitations'
      preLoaderRoute: typeof AdminUsersInvitationsRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/roles': {
      id: '/admin/users/roles'
      path: '/roles'
      fullPath: '/admin/users/roles'
      preLoaderRoute: typeof AdminUsersRolesRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/security': {
      id: '/admin/users/security'
      path: '/security'
      fullPath: '/admin/users/security'
      preLoaderRoute: typeof AdminUsersSecurityRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LandingRouteChildren {
  LandingLicenceRoute: typeof LandingLicenceRoute
  LandingPremiumRoute: typeof LandingPremiumRoute
  LandingPrivacyRoute: typeof LandingPrivacyRoute
  LandingRefundsRoute: typeof LandingRefundsRoute
  LandingTermsRoute: typeof LandingTermsRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingNewsletterConfirmRoute: typeof LandingNewsletterConfirmRoute
  LandingNewsletterUnsubscribeRoute: typeof LandingNewsletterUnsubscribeRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingLicenceRoute: LandingLicenceRoute,
  LandingPremiumRoute: LandingPremiumRoute,
  LandingPrivacyRoute: LandingPrivacyRoute,
  LandingRefundsRoute: LandingRefundsRoute,
  LandingTermsRoute: LandingTermsRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingNewsletterConfirmRoute: LandingNewsletterConfirmRoute,
  LandingNewsletterUnsubscribeRoute: LandingNewsletterUnsubscribeRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersAllRoute: typeof AdminUsersAllRoute
  AdminUsersInvitationsRoute: typeof AdminUsersInvitationsRoute
  AdminUsersRolesRoute: typeof AdminUsersRolesRoute
  AdminUsersSecurityRoute: typeof AdminUsersSecurityRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersAllRoute: AdminUsersAllRoute,
  AdminUsersInvitationsRoute: AdminUsersInvitationsRoute,
  AdminUsersRolesRoute: AdminUsersRolesRoute,
  AdminUsersSecurityRoute: AdminUsersSecurityRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLandingPageRoute: typeof AdminLandingPageRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingModelsRoute: typeof AdminPricingModelsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogCreateRoute: typeof AdminBlogCreateRoute
  AdminCoursesCreateRoute: typeof AdminCoursesCreateRoute
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLandingPageRoute: AdminLandingPageRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingModelsRoute: AdminPricingModelsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogCreateRoute: AdminBlogCreateRoute,
  AdminCoursesCreateRoute: AdminCoursesCreateRoute,
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppLicenseRoute: typeof AppLicenseRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLicenseRoute: AppLicenseRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTwoFactorRoute: typeof AuthTwoFactorRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTwoFactorRoute: AuthTwoFactorRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSplatRoute: typeof BlogSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSplatRoute: BlogSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
  ApiIndexRoute: ApiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
