export const AVATAR_INITIALS_START = 0
export const AVATAR_INITIALS_LENGTH = 2

export const EMPTY_STRING_LENGTH = 0
export const NON_EMPTY_COLLECTION_LENGTH = 1

export const PAGINATION_PAGE_ONE = 1
export const PAGINATION_PAGE_TWO = 2
export const PAGINATION_PAGE_THREE = 3
export const PAGINATION_FIRST_PAGE = PAGINATION_PAGE_ONE
export const PAGINATION_PAGES = [PAGINATION_PAGE_ONE, PAGINATION_PAGE_TWO, PAGINATION_PAGE_THREE] as const

export const EMPTY_PATH_PARTS_LENGTH = 0
