export const ROUTES = {
  HOME: "/",
  ADMIN: "/admin",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_COURSES: "/admin/courses",
  ADMIN_BLOG: "/admin/blog",
  ADMIN_LANDING_PAGE: "/admin/landing-page",
  ADMIN_PRICING: "/admin/pricing-models",
  ADMIN_CONTENT: "/admin/content-access",
  ADMIN_USERS: "/admin/users",
  ADMIN_SESSIONS: "/admin/sessions",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_SETTINGS: "/admin/settings",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  SIGN_IN: "/auth/sign-in",
  SIGN_UP: "/auth/sign-up",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  VERIFY_EMAIL: "/auth/verify-email",
} as const
