const TIMEZONES = {
  AMERICA_LOS_ANGELES: "America/Los_Angeles",
  AMERICA_NEW_YORK: "America/New_York",
  UTC: "UTC",
} as const

const TIMEZONE_VALUES = [TIMEZONES.UTC, TIMEZONES.AMERICA_NEW_YORK, TIMEZONES.AMERICA_LOS_ANGELES] as const

const DEFAULT_TIMEZONE = TIMEZONES.UTC

export const USER_PREFERENCES = {
  DEFAULT_TIMEZONE,
  TIMEZONES,
  TIMEZONE_VALUES,
} as const
